version: '3.3'
services:
  data_generator:
    build:
      context: ./data_generator
    image: ethfinance/ticker3:data_generator
    env_file:
      - ./settings/data_generator.secret
    ports:
      - 127.0.0.1:8081:80
  image_generator:
    build:
      context: ./image_generator
    image: ethfinance/ticker3:image_generator
    depends_on:
      - data_generator
    env_file:
      - ./settings/image_generator.secret
    volumes:
      - ./data:/data
    user: "0"
  reddit_uploader:
    build:
      context: ./reddit_uploader
    image: ethfinance/ticker3:reddit_uploader
    env_file:
      - ./settings/reddit_uploader.secret
    volumes:
      - ./data:/data